name: Bug report
description: Report something broken or incorrect
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect to happen instead?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `tach timer -M 5`
        2. Resize the terminal window
        3. ...
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14 / Ubuntu 24.04 / Windows 11
  - type: input
    id: terminal
    attributes:
      label: Terminal emulator
      placeholder: iTerm2, Terminal.app, Alacritty, Windows Terminal
  - type: input
    id: version
    attributes:
      label: Tach version
      placeholder: 0.0.0
